name: build

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:

  build_source_package:
    name: Build source package
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v5
        with:
          cache: 'pip'
          python-version: 3.13

      - name: Ensure build package is present
        run: python -m pip install setuptools

      - name: Build wheel for Python ${{ matrix.python-version }}
        run: python setup.py sdist

      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-oracledb-source
          path: dist

  build_linux_wheels:
    name: Build wheels for Linux
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: amd64
            container: docker.io/library/python:3.11-alpine
    steps:

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Generate script
        run: |
          echo "#!/bin/sh" > build.sh
          echo export PYO_COMPILE_ARGS=-g0 >> build.sh
          echo /opt/python/cp311-cp311/bin/python3.11 -m build >> build.sh
          echo cd dist >> build.sh
          echo auditwheel repair *.whl >> build.sh
          echo rm *.whl >> build.sh
          echo mv wheelhouse/*.whl . >> build.sh
          chmod +x build.sh

      - name: Build wheels
        run: |
          docker run \
            -v $(pwd):/io  \
            -w /io \
            --platform linux/${{ matrix.platform }} \
            ${{ matrix.container }} \
            ./build.sh

      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: Linux_${{ matrix.platform }}_wheels
          path: dist/*.whl

  combine_artifacts:
    name: Combine artifacts into single artifact
    needs: [build_source_package, build_linux_wheels]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/upload-artifact/merge@v4
        with:
          name: python-oracledb-wheels
          delete-merged: true
